# Generated by Django 5.0.6 on 2024-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_dealer_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='niche',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
