# Generated by Django 5.0.6 on 2024-05-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_dealer_niche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=100)),
                ('is_good', models.BooleanField(default=True)),
                ('is_bad', models.BooleanField(default=False)),
            ],
        ),
    ]
